server:
  port: 8095
  servlet:    context-path: /
spring:  datasource:
    #引入druid数据源
    type: com.alibaba.druid.pool.DruidDataSource    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/jtdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: root  

#spring-boot整合dubbo  
dubbo:
  scan:
    basePackages: com.jt #包扫描dubbo的service注解
  application:
    name: provider-order #提供者服务的名称
  registry: #连接zookeeper地址
    address: zookeeper://192.168.181.129:2181?backup=192.168.181.129:2182,192.168.181.129:2183
  protocol:
    name: dubbo
    port: 20882 #服务通信端口 消费者连接提供者端口

#mybatis-plush配置
mybatis-plus:  type-aliases-package: com.jt.pojo
  mapper-locations: classpath:/mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true  
#引入日志信息
logging:
  level: 
    com.jt.mapper: debug 